version: '3'

services:
  darts:
    container_name: darts
    image: postgres:latest
    environment:
      POSTGRES_DB: darts
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    networks:
      - darts
networks:
  darts:
    driver: bridge

volumes:
  postgresql_data:
    driver: local
  postgresql_bin:
    driver: local